server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ondot
    username: root
    password: root

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    generate-ddl: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: GOOGLE_ID
            client-secret: GOOGLE_SECRET
            scope:
              - email
              - profile

